"""add payment fields to booking model

Revision ID: 4f0c7f3501c4
Revises: 61894f3e4dea
Create Date: 2025-12-12 22:36:58.063514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f0c7f3501c4'
down_revision = '61894f3e4dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add payment fields to bookings table
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True, server_default='pending'))
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True, server_default='USD'))
        batch_op.add_column(sa.Column('payment_intent_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('paid_at')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_intent_id')
        batch_op.drop_column('currency')
        batch_op.drop_column('amount')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
